Fabricator(:analytic) do
  gclid_GA { FFaker::HTMLIpsum.body } 
  gclsrc_GA { FFaker::HTMLIpsum.body }
  gcn_GA { FFaker::HTMLIpsum.body }
  gid_GA { FFaker::HTMLIpsum.body }
  gt_GA { FFaker::HTMLIpsum.body }
  hc_GA { FFaker::HTMLIpsum.body }
  s_GA { FFaker::HTMLIpsum.body }
  ti_GA { FFaker::HTMLIpsum.body }
  to_GA { FFaker::HTMLIpsum.body }
  adSenseId_GA { FFaker::HTMLIpsum.body }
  allowAnchor_GA { FFaker::HTMLIpsum.body }
  allowLinker_GA { FFaker::HTMLIpsum.body }
  alwaysSendReferrer_GA { FFaker::HTMLIpsum.body }
  apiVersion_GA { FFaker::HTMLIpsum.body }
  clientId_GA { FFaker::HTMLIpsum.body }
  clientIdTime_GA { FFaker::HTMLIpsum.body }
  clientVersion_GA { FFaker::HTMLIpsum.body }
  cookieDomain_GA { FFaker::HTMLIpsum.body }
  cookieExpires_GA { FFaker::HTMLIpsum.body }
  cookieName_GA { FFaker::HTMLIpsum.body }
  cookiePath_GA { FFaker::HTMLIpsum.body }
  cookieUpdate_GA { FFaker::HTMLIpsum.body }
  encoding_GA { FFaker::HTMLIpsum.body }
  flashVersion_GA { FFaker::HTMLIpsum.body }
  javaEnabled_GA { FFaker::HTMLIpsum.body }
  language_GA { FFaker::HTMLIpsum.body }
  legacyCookieDomain_GA { FFaker::HTMLIpsum.body }
  legacyHistoryImport_GA { FFaker::HTMLIpsum.body }
  location_GA { FFaker::HTMLIpsum.body }
  name_GA { FFaker::HTMLIpsum.body }
  referrer_GA { FFaker::HTMLIpsum.body }
  sampleRate_GA { FFaker::HTMLIpsum.body }
  screenColors_GA { FFaker::HTMLIpsum.body }
  screenResolution_GA { FFaker::HTMLIpsum.body }
  siteSpeedSampleRate_GA { FFaker::HTMLIpsum.body }
  storage_GA { FFaker::HTMLIpsum.body }
  storeGac_GA { FFaker::HTMLIpsum.body }
  storedClientId_GA { FFaker::HTMLIpsum.body }
  trackingId_GA { FFaker::HTMLIpsum.body }
  useAmpClientId_GA { FFaker::HTMLIpsum.body }
  userId_GA { FFaker::HTMLIpsum.body }
  viewportSize_GA { FFaker::HTMLIpsum.body }
  XSRF_TOKEN_Cookie { FFaker::HTMLIpsum.body }
  ga_Cookie { FFaker::HTMLIpsum.body }
  ym_d_Cookie { FFaker::HTMLIpsum.body }
  ym_uid_Cookie { FFaker::HTMLIpsum.body }
  laravel_session_Cookie { FFaker::HTMLIpsum.body }
  date_Header { FFaker::HTMLIpsum.body }
  user_agent_Header { FFaker::HTMLIpsum.body }
  lang_Header { FFaker::HTMLIpsum.body }
  mobile_phone { FFaker::HTMLIpsum.body }
  ga_Cookie_G { FFaker::HTMLIpsum.body }
  gid_Cookie_G { FFaker::HTMLIpsum.body }
  L_Coockie_Y { FFaker::HTMLIpsum.body }
  Session_id_Cookie_Y { FFaker::HTMLIpsum.body }
  ym_d_Cookie_Y { FFaker::HTMLIpsum.body }
  ym_isad_Cookie_Y { FFaker::HTMLIpsum.body }
  ym_uid_Cookie_Y { FFaker::HTMLIpsum.body }
  bltsr_Cookie_Y { FFaker::HTMLIpsum.body }
  fuid01_Cookie_Y { FFaker::HTMLIpsum.body }
  i_Cookie_Y { FFaker::HTMLIpsum.body }
  mda_Cookie_Y { FFaker::HTMLIpsum.body }
  my_Cookie_Y { FFaker::HTMLIpsum.body }
  sessionid2_Cookie_Y { FFaker::HTMLIpsum.body }
  yabs_frequency_Cookie_Y { FFaker::HTMLIpsum.body }
  yabs_sid_Cookie_Y { FFaker::HTMLIpsum.body }
  yandex_gid_Cookie_Y { FFaker::HTMLIpsum.body }
  yandex_login_Cookie_Y { FFaker::HTMLIpsum.body }
  yandexuid_Cookie_Y { FFaker::HTMLIpsum.body }
  yc_Cookie_Y { FFaker::HTMLIpsum.body }
  yp_Cookie_Y { FFaker::HTMLIpsum.body }
  ys_Cookie_Y { FFaker::HTMLIpsum.body }
  zm_Cookie_Y { FFaker::HTMLIpsum.body }
  platform_Header { FFaker::HTMLIpsum.body }
  date { FFaker::HTMLIpsum.body }
  link { FFaker::HTMLIpsum.body }
  banner_id { FFaker::HTMLIpsum.body }
  pl_id { FFaker::HTMLIpsum.body }
  cpa { FFaker::HTMLIpsum.body }
  offer { FFaker::HTMLIpsum.body }
  image { FFaker::HTMLIpsum.body }
  event_type { FFaker::HTMLIpsum.body }
end
